export const instruments = [
  'cyBellRegular',
  // 'cyChinaRegular',
  'cyCowbellRegular',
  'cyCrashRegular',
  'cyRideRegular',
  // 'cySplashRegular',
  'hhCloseAccent',
  'hhCloseGhost',
  'hhCloseRegular',
  'hhFootRegular',
  'hhOpenAccent',
  'hhOpenGhost',
  'hhOpenRegular',
  'kiKickGhost',
  'kiKickRegular',
  'snRimRegular',
  'snSnareAccent',
  'snSnareGhost',
  'snSnareRegular',
  'toHighGhost',
  'toHighRegular',
  'toLowGhost',
  'toLowRegular',
  'toMidGhost',
  'toMidRegular',
] as const;
